# A. State preparation with Jaynes-Cummings controls

In [1]:
# ruff: noqa
import os

os.sys.path.append("..")
from feedback_grape.fgrape import optimize_pulse_with_feedback
from feedback_grape.utils.operators import (
    sigmap,
    sigmam,
    create,
    destroy,
    identity,
)
from feedback_grape.utils.states import basis, fock
from feedback_grape.utils.tensor import tensor
import jax.numpy as jnp
from jax.scipy.linalg import expm

As a preliminary step, we consider state preparation
of a target state starting from a pure state. In addition,
we assume that any coupling to an external environment
is negligible and that the parametrized controls can be
implemented perfectly.

Here no feedback is required, we are just testing the parameterized gates setup.

As a first example, we consider the state preparation
of a cavity resonantly coupled to an externally driven
qubit

Here, we consider a particular sequence of
parametrized unitary gates originally introduced by Law
and Eberly

In [2]:
N_cav = 30

In [3]:
def qubit_unitary(alpha_re, alpha_im):
    alpha = alpha_re + 1j * alpha_im
    return tensor(
        identity(N_cav),
        expm(-1j * (alpha * sigmap() + alpha.conjugate() * sigmam()) / 2),
    )

In [4]:
def qubit_cavity_unitary(beta_re, beta_im):
    beta = beta_re + 1j * beta_im
    return expm(
        -1j
        * (
            beta * (tensor(destroy(N_cav), sigmap()))
            + beta.conjugate() * (tensor(create(N_cav), sigmam()))
        )
        / 2
    )

In [5]:
# Uq = qubit_unitary(0.1, 0.1)
# Uqc = qubit_cavity_unitary(0.2, 0.2)
# print(
#     "Uq unitary check:",
#     jnp.allclose(Uq.conj().T @ Uq, jnp.eye(Uq.shape[0]), atol=1e-7),
# )
# print(
#     "Uqc unitary check:",
#     jnp.allclose(Uqc.conj().T @ Uqc, jnp.eye(Uqc.shape[0]), atol=1e-7),
# )

In [6]:
# qubit_unitary(0.1, 0.1).shape

In [7]:
# qubit_unitary(0.1, 0.1)

In their groundbreaking work, Law and Eberly have
shown that any arbitrary superposition of Fock states with
maximal excitation number N can be prepared out of the
ground state in a sequence of N such interleaved gates,
also providing an algorithm to find the correct angles and
interaction durations

In [8]:
# print(qubit_cavity_unitary(0.1, 0.1).shape)

In [9]:
# qubit_cavity_unitary(0.1, 0.1)

## First target is the state $ | 1 ⟩ + | 3 ⟩ $ 

In [10]:
# TODO: Why if time steps are less than 5 then it plateus at 0.5
time_steps = 5  # corressponds to maximal excitation number of an arbitrary Fock State Superposition

In [11]:
psi0 = tensor(basis(N_cav), basis(2))
psi0 = psi0 / jnp.linalg.norm(psi0)
psi_target = tensor((fock(N_cav, 1) + fock(N_cav, 3)) / jnp.sqrt(2), basis(2))
psi_target = psi_target / jnp.linalg.norm(psi_target)

In [12]:
psi0.shape

(60, 1)

In [13]:
psi_target.shape

(60, 1)

In [14]:
print(fock(N_cav, 1))

[[0.+0.j]
 [1.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]]


Law and Eberly provided an algorithm to determine the correct parameters for state preparation. These include:

- The rotation angle $ |\alpha| $,
- The azimuthal angle $ \arg\left(\frac{\alpha}{|\alpha|}\right) $,
- The interaction duration $ |\beta| $. <br>

So Goal is to find the best control vector (rather than control amplitudes, this time) that leads to finding the optimal state-preparation strategies. Performing as well as the Law-Eberly algorithm.

In [ ]:
# Answer: see why if initial [paramaters are complex, adam fidelity is so bad and l-bfgs does error]
# --> they only train real parameters, so we need to split the complex parameters into real and imaginary parts
import jax.random as random

key = random.PRNGKey(42)  # Random seed for reproducibility
num_gates = len(
    [qubit_unitary, qubit_cavity_unitary]
)  # Number of parameterized gates
# doing a .tolist() will lead to weird shape if you multiply outside with 5 or sth
# playing wiht the range will increase or decrease fidelity
initial_parameters = 5 * random.uniform(
    key,
    shape=(time_steps, num_gates, 2),
    minval=-jnp.pi,
    maxval=2 * jnp.pi,
)

print(f"Initial parameters: \n {initial_parameters}")

Initial parameters: 
 [[[  4.40109956 -15.00063041]
  [ 11.34795501  18.68394201]]

 [[ 16.70386422  14.63688792]
  [ 14.66972408  12.237571  ]]

 [[ -4.552878    -3.3220743 ]
  [ -4.30601676 -13.000761  ]]

 [[ 18.45859804  22.85768124]
  [ 12.01671016  -4.82850043]]

 [[-14.68603543  13.94188746]
  [ -5.23058656  29.91035793]]]


## Optimizing
Currently l-bfgs with the same learning rate of 0.3 converges at a local minimum of 0.5, adam also converges at 0.5 but at smaller learning rates

In [ ]:
from feedback_grape.utils.fidelity import ket2dm

result = optimize_pulse_with_feedback(
    U_0=ket2dm(psi0),
    C_target=ket2dm(psi_target),
    parameterized_gates=[qubit_unitary, qubit_cavity_unitary],
    initial_params=initial_parameters,
    num_time_steps=time_steps,
    max_iter=1000,
    convergence_threshold=1e-16,
    type="density",
    mode="no-measurement",
    # decay={
    #     "decay_indices": [0],  # indices of gates before which decay occurs
    #     # c_ops need to be tensored with the identity operator for the cavity
    #     # because it is used directly in the lindblad equation
    #     "c_ops": {
    #         # weird behavior when gamma is 0.00
    #         "tm": [tensor(identity(N_cav), jnp.sqrt(0.0015) * sigmam())],
    #         # "tc": [tensor(identity(N_cav), jnp.sqrt(0.15) * sigmap())],
    #     },  # c_ops for each decay index
    #     "tsave": jnp.linspace(0, 1, 2),  # time grid for decay
    #     "Hamiltonian": None,
    # },
    goal="fidelity",
    learning_rate=0.01,
    batch_size=10,
    eval_batch_size=2,
)

Iteration 0, Loss: -0.229757
Iteration 10, Loss: -0.323533
Iteration 20, Loss: -0.413270
Iteration 30, Loss: -0.499407
Iteration 40, Loss: -0.580201
Iteration 50, Loss: -0.637767
Iteration 60, Loss: -0.678976
Iteration 70, Loss: -0.707598
Iteration 80, Loss: -0.727199
Iteration 90, Loss: -0.741239
Iteration 100, Loss: -0.751868
Iteration 110, Loss: -0.760978
Iteration 120, Loss: -0.769543
Iteration 130, Loss: -0.777574
Iteration 140, Loss: -0.784895
Iteration 150, Loss: -0.792175
Iteration 160, Loss: -0.799421
Iteration 170, Loss: -0.806878
Iteration 180, Loss: -0.815495
Iteration 190, Loss: -0.824646
Iteration 200, Loss: -0.834923
Iteration 210, Loss: -0.847420
Iteration 220, Loss: -0.862772
Iteration 230, Loss: -0.880450
Iteration 240, Loss: -0.897683
Iteration 250, Loss: -0.916379
Iteration 260, Loss: -0.938340
Iteration 270, Loss: -0.953659
Iteration 280, Loss: -0.965005
Iteration 290, Loss: -0.973138
Iteration 300, Loss: -0.978818
Iteration 310, Loss: -0.983002
Iteration 320, Loss

In [17]:
len(result.returned_params)

5

In [18]:
jnp.array(result.returned_params)

Array([[[[  7.07763454, -17.47043701],
         [  7.07763454, -17.47043701]],

        [[ 13.51045793,  17.28620942],
         [ 13.51045793,  17.28620942]]],


       [[[ 16.03477984,  15.05020338],
         [ 16.03477984,  15.05020338]],

        [[ 14.38750315,  11.76628868],
         [ 14.38750315,  11.76628868]]],


       [[[ -4.1991143 ,  -4.67353736],
         [ -4.1991143 ,  -4.67353736]],

        [[ -4.85790597, -14.45215012],
         [ -4.85790597, -14.45215012]]],


       [[[ 20.75414028,  19.201602  ],
         [ 20.75414028,  19.201602  ]],

        [[ 12.03779372,  -3.23874888],
         [ 12.03779372,  -3.23874888]]],


       [[[-15.65740337,  15.44231068],
         [-15.65740337,  15.44231068]],

        [[ -6.1893385 ,  30.7913647 ],
         [ -6.1893385 ,  30.7913647 ]]]], dtype=float64)

In [19]:
print(result.final_state)

[[[ 4.49022836e-11-1.82705234e-24j -3.38099833e-08+1.51586205e-07j
    3.67647793e-06+2.96072216e-06j ...  0.00000000e+00+0.00000000e+00j
    0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]
  [-3.38099833e-08-1.51586205e-07j  5.37199684e-04-5.42101086e-20j
    7.22687031e-03-1.46407989e-02j ...  0.00000000e+00+0.00000000e+00j
    0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]
  [ 3.67647793e-06-2.96072216e-06j  7.22687031e-03+1.46407989e-02j
    4.96241258e-01+3.46944695e-18j ...  0.00000000e+00+0.00000000e+00j
    0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]
  ...
  [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
    0.00000000e+00+0.00000000e+00j ...  0.00000000e+00+0.00000000e+00j
    0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]
  [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
    0.00000000e+00+0.00000000e+00j ...  0.00000000e+00+0.00000000e+00j
    0.00000000e+00+0.00000000e+0

In [20]:
print(result)

FgResult(optimized_trainable_parameters=Array([[[  7.07763454, -17.47043701],
        [ 13.51045793,  17.28620942]],

       [[ 16.03477984,  15.05020338],
        [ 14.38750315,  11.76628868]],

       [[ -4.1991143 ,  -4.67353736],
        [ -4.85790597, -14.45215012]],

       [[ 20.75414028,  19.201602  ],
        [ 12.03779372,  -3.23874888]],

       [[-15.65740337,  15.44231068],
        [ -6.1893385 ,  30.7913647 ]]], dtype=float64), iterations=1000, final_state=Array([[[ 4.49022836e-11-1.82705234e-24j,
         -3.38099833e-08+1.51586205e-07j,
          3.67647793e-06+2.96072216e-06j, ...,
          0.00000000e+00+0.00000000e+00j,
          0.00000000e+00+0.00000000e+00j,
          0.00000000e+00+0.00000000e+00j],
        [-3.38099833e-08-1.51586205e-07j,
          5.37199684e-04-5.42101086e-20j,
          7.22687031e-03-1.46407989e-02j, ...,
          0.00000000e+00+0.00000000e+00j,
          0.00000000e+00+0.00000000e+00j,
          0.00000000e+00+0.00000000e+00j],
        [

In [21]:
result.final_fidelity

Array(0.99960653, dtype=float64)

In [22]:
# from feedback_grape.grape_paramaterized import calculate_trajectory
# from feedback_grape.utils.fidelity import fidelity

# U_final = calculate_trajectory(
#     U_0=psi0,
#     parameters=result.returned_params[0],
#     time_steps=time_steps,
#     parameterized_gates=[qubit_unitary, qubit_cavity_unitary],
#     propcomp="memory-efficient",
#     type="state",
#     decay=None,
# )
# print(
#     fidelity(C_target=psi_target, U_final=result.final_operator, type="state")
# )